config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  unauthenticated do
    root 'pages#index'
  end

  # Devise
  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register' },
    controllers: { 
      registrations: 'registrations'
    }

  # Resources
  resources :projects do
    resources :contacts
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  # Associations
  belongs_to :user
  belongs_to :project

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :project_id, presence: true
  validates :user_id, presence: true
  validates :mobile_number, presence: true, uniqueness: { scope: :project } 

  # Name
  def name
    [first_name, last_name].join(' ')
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :contacts

  # Validations
  validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :projects
  has_many :contacts
  
  # Validations
  validates_presence_of :first_name, :last_name, :mobile_phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected 

  # Devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :mobile_phone]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :mobile_phone]
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = current_user.contacts.build
  end

  def edit
  end

  def create
    @project = Project.find(params[:project_id])
    @contact = current_user.contacts.build(contact_params)
    @contact.project_id = @project.id

    if @contact.save
      redirect_to @project, notice: 'Contact was successfully created'
    else
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to root_path, notice: 'Contact successfully deleted'
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :mobile_number, :home_number)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    render layout: 'unauthenticated'
  end

  def home
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @project_contacts = @project.contacts
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, notice: 'You successfully created your Project'
    else
      render :new
    end
  end

  def update
    @project.update(project_params)
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: 'You successfully destroyed your Project'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :mobile_number %><br>
    <%= f.text_field :mobile_number %>
  </div>

  <div class="field">
    <%= f.label :home_number %><br>
    <%= f.text_field :home_number %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<!-- <h1>New contact</h1> -->

<%#= render 'form' %>

<%#= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_footer.html.erb
<footer>
  &copy; 2014 <%= link_to "Saphyre", root_path %>
</footer>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-left sidebar-nicescroller info-color">
  <ul class="sidebar-menu">

    <li class="nav-header">
      <div class="dropdown profile-element"> 
        <span>
          <img alt="image" src="http://webapplayers.com/inspinia_admin-v1.7/img/profile_small.jpg">
        </span>
        <div class="UserName">
          <%= current_user.first_name %> <%= current_user.last_name %>
        </div>
      </div>
    </li>

    <li>
      <%= link_to root_path do %>
        <i class="fa fa-dashboard icon-sidebar"></i>Dashboard
      <% end %>
    </li>

    <!-- Projects -->
    <% if params[:controller] == 'projects' %>
    <li class="selected active">
    <% else %>
    <li>
    <% end %>
      <a href="#">
        <i class="fa fa-send-o icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Projects
        <span class="label label-info span-sidebar">
          <%= current_user.projects.count %>
        </span>
        </a>
      <% if params[:controller] == 'projects' %>
      <ul class="submenu" style="display: block;">
      <% else %>
      <ul class="submenu">
      <% end %>

        <!-- Project Index -->
        <% if params[:controller] == 'projects' && params[:action] == 'index' %>
        <li class="selected">
        <% else %>
        <li>
        <% end %>
          <%= link_to projects_path do %>
            Overview
          <% end %>
        </li>

        <!-- New Project -->
        <% if params[:controller] == 'projects' && params[:action] == 'new' %>
        <li class="selected">
        <% else %>
        <li>
        <% end %>
          <%= link_to new_project_path do %>
            New Project
          <% end %>
        </li>

        <!-- Something else -->
        <li>
          <a href="#">
            Profile summary left
          </a>
        </li>
      </ul>
    </li>

    <!-- Contacts -->
    <li>
      <a href="#fakelink">
        <i class="fa fa-flask icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Contacts
      </a>
      <ul class="submenu">
        <li><a href="#">Default</a></li>
        <li><a href="#">Store</a></li>
        <li><a href="#">Real estate <span class="label label-danger span-sidebar">HOT</span></a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Social <span class="label label-danger span-sidebar">HOT</span></a></li>
      </ul>
    </li>



    <!--     
    <li class="static">EXTRA DESIGNS</li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-envelope icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Mail apps
        <span class="label label-danger span-sidebar">HOT</span>
      </a>
      <ul class="submenu">
        <li><a href="mail-inbox.html">Inbox <span class="badge badge-success span-sidebar">5</span></a></li>
        <li><a href="mail-send.html">Sent mail</a></li>
        <li><a href="mail-new.html">New mail</a></li>
        <li><a href="mail-contact.html">Mail contact</a></li>
        <li><a href="mail-read.html">Read mail</a></li>
        <li><a href="mail-reply.html">Reply mail</a></li>
      </ul>
    </li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-shopping-cart icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Store apps
      </a>
      <ul class="submenu">
        <li><a href="store-product-list.html">Product list</a></li>
        <li><a href="store-product-column.html">Product column</a></li>
        <li><a href="store-product-masonry.html">Product masonry</a></li>
        <li><a href="store-product-detail.html">Product detail</a></li>
        <li><a href="store-shopping-cart.html">Shopping cart</a></li>
        <li><a href="store-checkout.html">Checkout</a></li>
        
        <li><a href="store-orderlist.html">Order list</a></li>
        
      </ul>
    </li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-home icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Real estate apps
        </a>
      <ul class="submenu">
        <li><a href="real-estate-property-list.html">Property list</a></li>
        <li><a href="real-estate-property-column.html">Property column</a></li>
        <li><a href="real-estate-property-masonry.html">Property masonry</a></li>
        <li><a href="real-estate-property-detail.html">Property detail</a></li>
        <li><a href="real-estate-property-search.html">Search property</a></li>
      </ul>
    </li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-comment icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        <span class="label label-success span-sidebar">TOP</span>
        Blog apps
      </a>
      <ul class="submenu">
        <li><a href="blog-list.html">Blog list</a></li>
        <li><a href="blog-column.html">Blog column</a></li>
        <li><a href="blog-masonry.html">Blog masonry</a></li>
        <li><a href="blog-detail.html">Blog detail</a></li>
        <li><a href="blog-home.html">Featured home</a></li>
        <li><a href="blog-new.html">Add new blog</a></li>
        <li><a href="blog-comments.html">Comments</a></li>
      </ul>
    </li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-users icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Social apps
      </a>
      <ul class="submenu">
        <li><a href="social-home.html">Home activity</a></li>
        <li><a href="social-my-profile.html">My profile</a></li>
        <li><a href="social-friendlist.html">Friend list <span class="badge badge-info span-sidebar">5</span></a></li>
        <li><a href="social-timeline.html">Timeline</a></li>
        <li><a href="social-photos.html">Photos</a></li>
      </ul>
    </li>

    <li>
      <a href="#fakelink">
        <i class="fa fa-heart icon-sidebar"></i>
        <i class="fa fa-angle-right chevron-icon-sidebar"></i>
        Example pages
      </a>
      <ul class="submenu">
        <li><a href="login.html">Login</a></li>
        <li><a href="lock-screen.html">Lock screen</a></li>
        <li><a href="forgot-password.html">Forgot password</a></li>
        <li><a href="register.html">Register</a></li>
        <li><a href="example-pricing-table.html">Pricing table</a></li>
        <li><a href="example-invoice.html">Invoice</a></li>
        <li><a href="example-faq.html">FAQ</a></li>
        <li><a href="example-search.html">Search page</a></li>
        <li><a href="404.html">404</a></li>
        <li><a href="blank.html">Blank page</a></li>
      </ul>
    </li>
    -->
    

  </ul>
</div><!-- /.sidebar-left -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saphyre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>


<div class="wrapper">

  <!-- Navbar -->
  <%= render 'layouts/header' %>
  
  <!-- Sidebar Left -->
  <%= render 'layouts/sidebar' %>
  
  <!-- Sidebar Right -->
  <%= render 'layouts/right_nav' %>
  
  <!-- Page Content -->
  <div class="page-content">

    <div class="container">
    
      <!-- Flash Message -->
      <% flash.each do |name, msg| %>
        <div class="alert alert-info alert-bold-border fade in alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p class="text-muted">
            <%= msg %>
          </p>
        </div>
      <% end %>

    </div><!-- /.container -->

      <!-- Content -->
      <%= yield %>

    
    
    <!-- FOOTER -->
    <%= render 'layouts/footer'  %>

  </div><!-- /.page-content -->
</div><!-- /.wrapper -->


</body>
</html>

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saphyre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!-- Begin page heading -->
<h1 class="page-heading">Dashboard <small>Sub heading here</small></h1>

<div class="jumbotron center">
   <h1>Welcome to my app!</h1>
   <% if user_signed_in? %>
        # do something
   <% else %>
     <p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
     </p>
  <% end %>  
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
    <% end %>  
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1 class="page-heading">Projects <small>Sub heading here</small></h1>

<ol class="breadcrumb default rsaquo sm">
  <li>
    <%= link_to root_path do %>
      <i class="fa fa-home"></i>
    <% end %>
  </li>
  <li class="active">Projects</li>
</ol>

<div class="panel ProjectsIndex">
  <table class="table table-hover">
    <tbody>

      <% @projects.each do |project| %>
        <tr>
          <td class="project-status">
            <span class="label label-primary">
              Send
            </span>
          </td>
          <td class="ProjectTitle">
            <%= link_to project.name, project %>
            <br>
            <small class="text-muted">Created 14.08.2014</small>
          </td>
          <td class="project-people">
            ss
          </td>
          <td class="project-actions clearfix">
            <div class="pull-right">
              <%= link_to project, class: 'btn btn-info btn-sm' do %>
                <i class="fa fa-folder"></i> View 
              <% end %>
              <a href="#" class="btn btn-info btn-sm">
                <i class="fa fa-pencil"></i> Edit 
              </a>
            </div>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h1 class="page-heading">New Project <small>Sub heading here</small></h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">

    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="NewProject text-center">
      <%= form_for(@project) do |f| %>

        <div class="form-group">
          <%= f.text_field :name, class: 'BigInput', placeholder: 'Project name', autofocus: true, required: true, autocomplete: 'off' %>
        </div>

        <div class="form-group">
          <%= button_tag(type: "submit", class: "btn btn-info") do %>
            <i class="fa fa-plus"></i> Create Project
          <% end %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/projects/show.html.erb
<div class="the-box bg-dark no-border no-margin heading">
  <div class="row">
    <div class="col-sm-6">
      <h1>
        <i class="fa fa-suitcase icon-lg icon-circle icon-bordered"></i>
        <%= @project.name.capitalize %>
      </h1>
    </div><!-- /.col-sm-6 -->
    <div class="col-sm-6 text-right">
      <button class="btn btn-info btn-sm"><i class="fa fa-cloud-upload"></i></button>
      <div class="btn-group">
        <button class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-cog"></i>
        </button>
        <ul class="dropdown-menu info pull-right square margin-list text-left" role="menu">
          <li><a href="#fakelink">Action</a></li>
          <li><a href="#fakelink">Another action</a></li>
          <li class="active"><a href="#fakelink">Active</a></li>
          <li class="divider"></li>
          <li><a href="#fakelink">Separated link</a></li>
        </ul>
      </div>
    </div><!-- /.col-sm-6 -->
  </div><!-- /.row -->
</div>

<br>

<div class="container">
    
  <div class="row">
    <div class="col-md-9">
     <section class="panel">

      <table class="table table-bordered table-hover table-condensed list_specific_index_table">
        <thead>
          <tr class="filters">

            <th>
              Name         
            </th>

            <th>
              Mobile Number
            </th>

            <th class="text-center">
              Response
            </th>

            <th class="text-center" style="width: 150px">
              Touched
            </th>

            <th class="text-center">
              Spec
            </th>

            <th class="text-center">Action</th>

          </tr>
        </thead>
        <tbody>

          <% @project_contacts.each do |contact| %>
            <tr>
              <td width="250px">
                Alefantinos
              </td>

              <td width="1000px">
                Alefantinos
              </td>

              <td width="180px" class="text-center response_td">
                  <i class="fa fa-circle"></i>
              </td>

              <td width="180px" class="text-center touched_td">
                  <i class="fa fa-bolt"></i>
              </td>

              <td width="150px" class="text-center bug_td">
                  <i class="fa fa-bug"></i>
              </td>

              <td width="150px" class="text-center">          
                <%= link_to project_contact_path(@project, contact), class: 'btn btn-info btn-xs' do %>
                  <i class="fa fa-comment"></i> &nbsp; <b>Show</b>
                <% end %>
              </td>
            </tr>
          <% end %>
            
        </tbody>
      </table>
    </section>
    </div>
    <div class="col-md-3">
      
      <div class="the-box no-border bg-dark rounded tiles-information">
        <i class="fa fa-users icon-bg"></i>
        <div class="tiles-inner text-center">
          <p>Contacts in Project</p>
          <h1 class="bolded"><%= @project.contacts.count %></h1> 
          <div class="progress no-rounded progress-xs">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
            </div><!-- /.progress-bar .progress-bar-info -->
          </div><!-- /.progress .no-rounded -->
          <p><small>Better than yesterday ( 2,5% )</small></p>
        </div><!-- /.tiles-inner -->
      </div>

      <ul class="nav nav-tabs right-position">
        <li class="active"><a href="#fakelink">Overview</a></li>
        <li><a href="#fakelink">Contacts</a></li>
        <li><a href="#fakelink">Import</a></li>
      </ul>



    </div>
  </div>
</div>